-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: check-ast
    -   id: autopep8-wrapper
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.4
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/asottile/add-trailing-comma
    sha: v0.6.3
    hooks:
    -   id: add-trailing-comma
